### ISSUE TITLE
Add checkpoints to build_from.py

### ISSUE THREAD

**Issue by cmc333333** [18F/regulations-parser#17]
Right now, building a regulation is incredibly painful, particularly when something goes wrong. This is in large part because re-running the _working_ steps takes so long.

Add the ability for build_from.py to checkpoint its progress so that future runs don't require as much rework. As part of this, merge in https://github.com/cfpb/regulations-parser/pull/262

**Comment by grapesmoker** [comment]
This is something that, pending approval from product owners in CFPB, we're going to try and work on in the coming sprint. We should probably pool our efforts on this.
