### ISSUE TITLE
Split parsing into phases

### ISSUE THREAD

**Issue by cmc333333** [18F/regulations-parser#6]
Right now, we've got a single `build_from.py` script, which
  1. parses the initial XML file to generate an initial tree
  1. reads and parses all notice XML files
  1. writes the initial tree
  1. generates and writes layers based on that initial XML
  1. incrementally builds revisions
  1. writes those out, along with their layers
  1. calculates diffs between layers and writes those out

This pipeline works well when there's no parsing errors, but when there are, it can be a *very* long time before developers find them (as they wait for the other phases to end). While each of these steps is relatively self contained in terms of code, there aren't entry points to run each individually.

One could imagine one of the above phases fails, the developer figures out why, provides a fix, and then retests *from that point*.

**Comment by ultrasaurus** [comment]
Do we have an example of one that fails?  would be helpful for someone new getting started on this

**Comment by micahsaul** [comment]
I believe every regulation in 11 CFR other than 110 will fail, currently. I
can't remember exactly, though.

**Comment by cmc333333** [comment]
This was resolved with the `pipeline` / `eregs` command
